### ISSUE TITLE
Current solution to build for macos ARM64

### ISSUE THREAD

**Issue by jeandet** [FFY00/meson-python#131]
Hello,

I wonder what are the actual solutions to build macos/ARM64 packages with public CI services available like GH Actions.
It seems that GH Actions hasn't released the support for M1 yet: https://github.com/github/roadmap/issues/528
The only other solution I could think of, would be cross compilation but I don't think that's possible yet with meson-python?
Did I miss something?

**Comment by rgommers** [comment]
GitHub Actions is going to take a while longer I suspect. I did just learn of Cirrus CI, which seems to be the first to offer M1 support free for open source projects: https://cirrus-ci.org/guide/macOS/#macos-virtual-machines. I haven't tried it myself yet, but it looks promising.

Qemu probably doesn't work on macOS arm64 yet? Can't find any info so quickly.

> The only other solution I could think of, would be cross compilation but I don't think that's possible yet with meson-python?

I'm working on that for SciPy; part 1 is making cross-compilation work when using `meson` directly (basically there with one hacky bit), part 2 is to supply a cross file to `pip` or `build` and have that picked up correctly.

**Comment by jeandet** [comment]
I didn't know either cirrus! Awesome, it seems indeed to provide ARM64 machines:

![Screenshot from 2022-08-19 20-46-51](https://user-images.githubusercontent.com/7570249/185686994-24563918-4043-43a7-ae5d-2fd176d59024.png)

I'll try to use that to publish on PyPi.

**Comment by rgommers** [comment]
Great, would love to hear how it works out for you!

**Comment by jeandet** [comment]
Well so far, I was able to build a wheel (still using my wrapper script to get the right name) \o/:
```
Found one wheel to rename dist/pycdfpp-0.4.0-cp310-cp310-any.whl
New wheel name: dist/pycdfpp-0.4.0-cp310-cp310-macosx_12_0_arm64.whl
```

It's pretty fast and the UI is quite nice:

![Screenshot from 2022-08-19 21-10-32](https://user-images.githubusercontent.com/7570249/185690451-33b1c7cf-b8f0-44bc-9a3f-cc3c05e95080.png)

My current .currus.yml file is:

```
macos_instance:
  image: ghcr.io/cirruslabs/macos-monterey-base:latest

task:
  script: |
    brew install gcc@11 pyenv
    pyenv install 3.10.4
    export PATH="~/.pyenv/shims:${PATH}"
    pyenv local 3.10.4
    pip3 install meson build wheel twine
    CC=gcc-11 CXX=g++-11 python3 scripts/build_wheel.py
```

Next steps are:
- find how to filter github releases
- do it for all python versions if possible with build matrix if it exists
- register secrets to push on PyPi

And that should be enough.

**Comment by jeandet** [comment]
Finally I was able to build and push on test.pypi with the following script:
https://github.com/SciQLop/CDFpp/blob/2b7d9d43712e58aa6b7fb429e50802038e837cac/.cirrus.yml

Note that the yml can be quite tricky to write and also you have some strong concurrency limitations for free projects, only one task at the time plus some delay between tasks. But it works pretty well! Thank you for the pointer :).

**Comment by rgommers** [comment]
Thanks for sharing @jeandet, very useful!

**Comment by tylerjereddy** [comment]
Cool stuff, it seems to work quite well in my tests on the two cross-linked medium size Python projects as well.
