### ISSUE TITLE
Sage CI jobs seem to build SciPy 1.8.1

### ISSUE THREAD

**Issue by rgommers** [FFY00/meson-python#150]
Here is an example log from just now: https://github.com/FFY00/meson-python/actions/runs/3144590900/jobs/5110809044. @mkoeppe do you have any idea what changed? Testing SciPy 1.8.1 isn't going to reveal much about `meson-python`.

We now have much better tests as well, so perhaps we want to consider changing the Sage test suite to only run the `meson-python` test suite. That'll be way faster, and then we get more signal on the variation across Linux distros. The `scipy-like ` test case in gh-145 will be especially useful to run there, and cover similar ground as the full SciPy build.

**Comment by mkoeppe** [comment]
Fixed by pushing changes to the branch on https://trac.sagemath.org/ticket/34081

It runs `meson-python`'s pytest now - https://git.sagemath.org/sage.git/commit/?id=433b2e9658be0a42e3382a905d79a225cb7f968d

**Comment by rgommers** [comment]
Thanks @mkoeppe. The builds at https://github.com/FFY00/meson-python/actions/runs/3145818275/jobs/5113637396 seem to be failing though, with:
```
Target 'meson_python' not remade because of errors
```

**Comment by mkoeppe** [comment]
Fixed already in https://trac.sagemath.org/ticket/34081 (https://git.sagemath.org/sage.git/commit/?id=bce99d207802265cdfd4ad9570856e2aaf22bf32)

**Comment by FFY00** [comment]
Thanks! I am re-running the CI in #136 because it was failing due to this. Let's see if it works now.

**Comment by mkoeppe** [comment]
There's another problem, I'm on it

**Comment by mkoeppe** [comment]
```
 [meson_python-git]   tests/conftest.py:11: in <module>
  [meson_python-git]       import git
  [meson_python-git]   ../../../../../../lib/python3.10/site-packages/git/__init__.py:89: in <module>
  [meson_python-git]       raise ImportError('Failed to initialize: {0}'.format(exc)) from exc
  [meson_python-git]   E   ImportError: Failed to initialize: Bad git executable.
  [meson_python-git]   E   The git executable must be specified in one of the following ways:
  [meson_python-git]   E       - be included in your $PATH
  [meson_python-git]   E       - be set via $GIT_PYTHON_GIT_EXECUTABLE
  [meson_python-git]   E       - explicitly set via git.refresh()
```
It's a bit inconvenient that testing meson-python needs a git executable - which is not pip-installable

**Comment by mkoeppe** [comment]
Fixed by #152 I think

**Comment by mkoeppe** [comment]
I've pushed another fix for the `archlinux` platform to https://trac.sagemath.org/ticket/34081, but the rest of the failures are now pytest failures that look genuine to me

**Comment by mkoeppe** [comment]
I think this can be closed now

**Comment by FFY00** [comment]
Thank you so much for the help @mkoeppe!
