### ISSUE TITLE
Windows f2py created linking

### ISSUE THREAD

**Issue by greglucas** [FFY00/meson-python#178]
I'm trying to port a Fortran wrapper over to use meson from numpy.distutils and think I've got it close, but I am unclear if I need to do anything special with the DLL paths on Windows to be able to import the libraries after package installation. I have tried adding various configurations of `os.add_dll_directory` and `sys.path` to no avail.

I'm wondering if this statement means there is a known issue with linking libraries on Windows?

> Windows 🔨
Does not support linking against libraries from the Meson project

My issue is that it seems like the wheel gets built properly and there are `.pyd` and `.dll.a` files created where I'd expect them in the base of the project, but going to import them I get:
```
E   ImportError: DLL load failed while importing msis00f: The specified module could not be found.
```

Link to the PR where all of the osx and linux builds succeed, but the Windows one fails: https://github.com/SWxTREC/pymsis/pull/21

This could be something very obvious I'm missing on my part with modifying the system paths, but it did work with numpy.distutils / setuptools, which is why I'm wondering if I need to add any additional configuration to the meson-python build? (I don't have access to a Windows box, so unfortunately I'm at the mercy of CI for all of the testing)

**Comment by rgommers** [comment]
It looks like it's all the `.pyd` and `dll.a.` files that generate that warning. You do not need to install the `.dll.a` files right? Those are static libraries, while you only need the `.pyd` Python extension modules?

I see in your CI log that you are using `meson-python` 0.8.1 and `meson` 0.63.2. The 0.9.0 and 0.63.3 versions have fixes for these issues. Can you update to the latest version of each package and try again?

> Does not support linking against libraries from the Meson project

That sentence is confusing and we should update it. It only talks about if you have standalone non-Python shared libraries that you want to put into your wheel, and depend on them from a Python extension, then there's an issue.

**Comment by rgommers** [comment]
Ah, I was confused about why it didn't use the latest versions - but your CI log is from a month ago. I think the issue you saw is fixed now.

**Comment by greglucas** [comment]
Ahh, sorry, I should have pushed a new version before posting here. I've been banging on CI on my local fork instead of cluttering that PR. I just pushed a new run over there that fails in the same manner with the updated minimum versions you suggested:
https://github.com/SWxTREC/pymsis/actions/runs/3260271414/jobs/5353713868

> You do not need to install the .dll.a files right? Those are static libraries, while you only need the .pyd Python extension modules?
I believe that is correct, but I do not have enough knowledge about Windows to say for certain.

**Comment by greglucas** [comment]
Closing this issue here as this isn't a problem with meson-python. It ended up that even using meson directly and going into the install directory also had the import issue on Windows. The issue is that on Windows with gcc compilers you need to statically link in libgfortran to the created *.pyd files.

Specifically on Scipy this is found in this code block:
https://github.com/scipy/scipy/blob/a082eb415192f3075921fbf3e539f2b82a53811e/scipy/meson.build#L5-L7

Thanks for the quick response and help!
