### ISSUE TITLE
entry-point and other metadata management

### ISSUE THREAD

**Issue by kif** [FFY00/meson-python#184]
Hi,
I am trying to migrate some projects from setuptools+numpy-distutils `to meson-python`. Apparently the wheels generated are valid and both the modules and extensions are at the proper place in it. But I did not figure out how to have entry-point properly declared.

https://github.com/kif/fabio/blob/meson/pyproject.toml

With `setuptools`,  wheels had a `dist-info/entry-points.txt` containing the list of scripts to generate at installation.
Apparently, this is now done with [project.scripts] in the `pyproject.toml` file but no entry-point is generated from then. Do you have an idea of what could go wrong ?

Thanks for your help.

Jerome

**Comment by eli-schwartz** [comment]
AFAICT https://packaging.python.org/en/latest/specifications/entry-points/ isn't actually handled anywhere right now, although manually written scripts installed from meson.build to `get_option('bindir')` should be handled correctly -- i.e. they are packed into the wheel as `{distribution}-{version}.data/scripts/`.

That could be considered a stopgap measure I suppose.

**Comment by FFY00** [comment]
You are right, I just looked at the code, and it seems we are not generating the `entrypoints.txt` file. This was a big oversight, I thought we already had that implemented. Sorry.
