### ISSUE TITLE
Replace pep621 dependency

### ISSUE THREAD

**Issue by FFY00** [FFY00/meson-python#33]
`pep621` will be renamed `pyproject-metadata`, so we will need to replace the dependency here.

See https://github.com/FFY00/python-pep621/issues/10

At this point, https://github.com/pypa/packaging does not yet provide this functionality.

**Comment by rgommers** [comment]
There seems to be a more urgent issue here: `pep621` is imported here: https://github.com/FFY00/meson-python/blob/main/mesonpy/__init__.py#L552-L553 but is not declared as a dependency. So I'm seeing:
```
ModuleNotFoundError: No module named 'pep621'
```
in the CI job that tests building via sdist for SciPy ([log](https://dev.azure.com/scipy-org/SciPy/_build/results?buildId=18207&view=logs&j=5428a243-ce9d-5a90-882b-245b865f3bbe&t=61cfec6f-65f8-54f8-b88d-e2ddf9ae8303). Why is a non-optional dependency not declared? The comment even explicitly discusses raising an exception - it should not be necessary for `meson-python` users like SciPy to list `pep621` as a direct dependency. It should be either vendored, declared as non-optional, or made actually optional.
