### ISSUE TITLE
Prios for releasing SciPy 1.9.0 with `meson-python` as default

### ISSUE THREAD

**Issue by rgommers** [FFY00/meson-python#57]
The SciPy 1.9.x release branch creation is planned for May 26th, and we still haven't been able to switch to using `meson-python` in `pyproject.toml`. So this is getting kind of urgent. Let me outline what I think we need to not be blocked.

Release branch creation blocker (highest prio):
- [x] gh-52 (a blocker because isolated builds are completely broken on Linux right now for any user of `meson-python` as far as I can tell)

Release blockers:
- [x] gh-53 (this can be worked around for release candidates if needed, but even that is cumbersome - and I think not being able to apply any patches is enough of an impact on downstream packagers to consider it a release blocker)
- [x] gh-56 (this make `pip install . --no-build-isolation` too fragile)

The rest of the currently known issues are all nice-to-have I think. The prio of these I'd say is (1 being highest):
1. gh-47
2. gh-54
3. gh-29

**Comment by rgommers** [comment]
The plan is to release 0.5.0 today or tomorrow with at least the `patchelf-wrapper` and `pep621` fixes. Ideally also the "uncommitted changes" fix, but if needed that can wait a few days - it is important for generating an sdist (so last SciPy release candidate at least), but not for merging https://github.com/scipy/scipy/pull/16187

**Comment by FFY00** [comment]
There is a weird issue with the sdist generation preventing me from making a release. In some situations, which I haven't figured out yet, the generated tar file is corrupted. I have been trying to figure it how, but haven't been able to identify the issue, I will have to finish tomorrow.

**Comment by FFY00** [comment]
Tracked down the issue, I will be pushing the release soon, sorry for the delay!

**Comment by rgommers** [comment]
Great, thanks

**Comment by FFY00** [comment]
https://pypi.org/project/meson-python/0.5.0/ is now available. Let me know if you run into any other issue.
