### ISSUE TITLE
SciPy wheel builds on Debian/Ubuntu through meson-python are broken

### ISSUE THREAD

**Issue by rgommers** [FFY00/meson-python#74]
See https://github.com/scipy/scipy/issues/16300. Particularly relevant comments there:

**1. https://github.com/scipy/scipy/issues/16300#issuecomment-1140482018**

It's indeed the case though that this line is coming from `meson-python`:
```
WARNING File could not be mapped to an equivalent wheel directory: /home/treddy/github_projects/scipy/.mesonpy-j3f51rro/install/usr/lib/python3/dist-packages/scipy/_lib/_ccallback_c.cpython-310-x86_64-linux-gnu.so ({moduledir_shared}/_ccallback_c.cpython-310-x86_64-linux-gnu.so)
```
The [_map_from_heuristics](https://github.com/FFY00/meson-python/blob/main/mesonpy/__init__.py#L200) has Debian-specific handling, I just don't understand why it's going wrong here. Either way, it shouldn't silently discard install targets. @FFY00 can you enlighten us here?

**2. https://github.com/scipy/scipy/issues/16300#issuecomment-1140842027**

Given that meson >= 0.62 correctly handles debian derivatives including venvs with its venv='auto' switch, I actually wonder why pep517 wrapper even needs to handle it separately, and if it can does for some reason, whether it can just reuse relevant logic from meson itself.

**Comment by rgommers** [comment]
`return None` discards the file, rather than raise an error. Here: https://github.com/FFY00/meson-python/blob/main/mesonpy/__init__.py#L232

**Comment by FFY00** [comment]
> The [_map_from_heuristics](https://github.com/FFY00/meson-python/blob/main/mesonpy/__init__.py?rgh-link-date=2022-06-10T12%3A22%3A40Z#L200) has Debian-specific handling, I just don't understand why it's going wrong here. Either way, it shouldn't silently discard install targets. @FFY00 can you enlighten us here?

There are two things here, first the "placeholdered" path that we get from Meson uses `{moduledir_shared}`, which is currently is not adding the subdirs, so we can't do a direct mapping. Secondly, heuristics are somehow failing to catch this case, which is a bit weird.

> `return None` discards the file, rather than raise an error. Here: [https://github.com/FFY00/meson-python/blob/main/mesonpy/__init__.py#L232](https://github.com/FFY00/meson-python/blob/main/mesonpy/__init__.py?rgh-link-date=2022-06-10T12%3A57%3A50Z#L232)

Yes, `None` means no match was found. We issue a warning afterwards, the file isn't silently ignored.

https://github.com/FFY00/meson-python/blob/main/mesonpy/__init__.py#L272

**Comment by FFY00** [comment]
This is a bug in the Debian heuristics. I've tracked it down and have a fix.

**Comment by FFY00** [comment]
I validated it on a Debian Sid docker btw, and have opened #76 regarding having a CI job that run the whole testsuite in a Debian Python.

**Comment by ev-br** [comment]
> @ev-br since you can reproduce the issue locally, would you mind testing this (EDIT: the fix in gh-77)?

Sure. How?

**Comment by rgommers** [comment]
You could reproduce in https://github.com/scipy/scipy/issues/16300#issuecomment-1140520018. I think the easiest way to repro is:
1. change the build command to `pip install . --no-build-isolation` and see if it still reproduces (it should, after installing `meson-python` from PyPI
2. install `meson-python` from this branch (check it out, then `pip install .`)
3. see that the problem is gone

**Comment by tylerjereddy** [comment]
I'm checking now, well writing up my results.. note that there's definitely an issue with the `pep621` package update, but for the sake of testing this I will roll that back locally.. just give me a minute and I'll link the comment in this issue as well..

**Comment by tylerjereddy** [comment]
I think you're good to go now with that branch + the latest of `pep621` as per the details of my checking here: https://github.com/FFY00/meson-python/pull/77#pullrequestreview-1003364968

This should also unblock https://github.com/scipy/scipy/pull/16353#issuecomment-1151711888 as per my comments above, though the situation is indeed confusing.

**Comment by ev-br** [comment]
Took me a while to get to it, sorry about that. Scipy seems to build and pass test locally for me with gh-77 and `pip install . --no-build-isolation` after `sudo apt install patchelf` in addition to python-level dependencies:

```
>>> scipy.test()
<a bunch of warnings from scipy.statss>
= 37420 passed, 2665 skipped, 12000 deselected, 137 xfailed, 12 xpassed, 46 warnings in 524.58s (0:08:44) =
True
```

**Comment by rgommers** [comment]
Thanks for verifying @tylerjereddy and @ev-br! That solves one hairy issue for 1.9.0 🎉
