### ISSUE TITLE
Run tests against Debian Python in CI

### ISSUE THREAD

**Issue by FFY00** [FFY00/meson-python#76]

**Comment by rgommers** [comment]
We test this in SciPy `main` now. That CI job may also be a useful reference if someone wants to work on adding a similar job on this repo: https://github.com/scipy/scipy/blob/2cea593ce9c59b223f9f347daa26fc7e93b57584/.github/workflows/linux_meson.yml#L102-L134

**Comment by FFY00** [comment]
Thank you!
